"""
generator.py — consultancy-grade report generation (Markdown + PDF).

For each finding we emit a structured Markdown report containing everything a
program needs to triage and fix it: full HTTP request/response, numbered repro
steps, exact payload + context, the visual PoC, root-cause, CVSS v3.1 +
business impact, context-specific remediation, and CWE/OWASP references. We also
emit ONE consolidated report covering every finding.

PDFs are produced by rendering the report's HTML in the same headless Chromium
we already use for verification (no heavy native PDF dependencies). If Playwright
isn't available, Markdown is still produced and PDF is skipped with a note.

Each per-finding report also carries a clearly-marked "Learning notes" section
(generated by the explain engine for YOU) — delete it before submitting.
"""

from __future__ import annotations

import base64
import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from core.context import PlatformContext
from report.cvss import score_for_subtype
from report.explain import explain_finding
from report.remediation import remediation_for

_CSS = """
body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
       margin: 40px; color: #1a1a1a; line-height: 1.5; }
h1 { border-bottom: 3px solid #2c3e50; padding-bottom: 8px; }
h2 { color: #2c3e50; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-top: 28px; }
h3 { color: #34495e; }
code, pre { font-family: SFMono-Regular, Consolas, monospace; }
pre { background: #f5f5f5; border: 1px solid #ddd; border-radius: 4px; padding: 12px;
      overflow-x: auto; white-space: pre-wrap; word-wrap: break-word; font-size: 12px; }
code { background: #f0f0f0; padding: 1px 4px; border-radius: 3px; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; }
th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; }
th { background: #2c3e50; color: #fff; }
img { max-width: 100%; border: 1px solid #ccc; border-radius: 4px; margin: 10px 0; }
.sev-critical { color: #fff; background: #c0392b; padding: 2px 8px; border-radius: 3px; }
.sev-high { color: #fff; background: #e74c3c; padding: 2px 8px; border-radius: 3px; }
.sev-medium { color: #fff; background: #e67e22; padding: 2px 8px; border-radius: 3px; }
.sev-low { color: #fff; background: #f1c40f; padding: 2px 8px; border-radius: 3px; }
.learning { background: #eef7ff; border-left: 4px solid #3498db; padding: 12px; margin: 16px 0; }
"""


class ReportGenerator:
    def __init__(
        self,
        ctx: PlatformContext,
        out_dir: str | Path = "data/reports",
        logger: logging.Logger | None = None,
    ) -> None:
        self.ctx = ctx
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.log = logger or logging.getLogger("report")

    # -- public API --------------------------------------------------------
    def generate_all(self, only_verified: bool = False, make_pdf: bool = True) -> dict:
        ds, pid = self.ctx.datastore, self.ctx.program_id
        findings = ds.get_findings(pid, status="verified") if only_verified else ds.get_findings(pid)
        if not findings:
            self.log.warning("No findings to report.")
            return {"reports": 0, "consolidated": ""}

        per_finding_md: list[tuple[Any, str]] = []
        for f in findings:
            # Backfill CVSS onto the finding so the dashboard can show it too.
            cvss = score_for_subtype(f["subtype"] or "reflected")
            if cvss.vector:
                ds.update_finding_fields(f["id"], cvss_score=cvss.score, cvss_vector=cvss.vector)
            md = self._finding_markdown(f, cvss)
            per_finding_md.append((f, md))

            stem = f"finding-{f['id']}-{(f['subtype'] or 'xss')}"
            (self.out_dir / f"{stem}.md").write_text(md, encoding="utf-8")
            if make_pdf:
                self._render_pdf(md, self.out_dir / f"{stem}.pdf")

        consolidated = self._consolidated_markdown(findings, per_finding_md)
        consolidated_path = self.out_dir / "consolidated-report.md"
        consolidated_path.write_text(consolidated, encoding="utf-8")
        if make_pdf:
            self._render_pdf(consolidated, self.out_dir / "consolidated-report.pdf")

        self.log.info("Generated %d report(s) in %s", len(findings), self.out_dir)
        return {
            "reports": len(findings),
            "consolidated": str(consolidated_path),
            "out_dir": str(self.out_dir),
        }

    # -- per-finding -------------------------------------------------------
    def _finding_markdown(self, f: Any, cvss) -> str:
        evidence = _load_evidence(f["evidence"])
        subtype = f["subtype"] or "reflected"
        context = f["context"] or ""
        rem = remediation_for(subtype, context)
        sev = (cvss.rating if subtype != "csp" else f["severity"]) or f["severity"]

        md: list[str] = []
        md.append(f"# {f['title'] or 'XSS finding'}")
        md.append("")
        md.append("| Field | Value |")
        md.append("|---|---|")
        md.append(f"| Type | Cross-Site Scripting ({subtype}) |")
        md.append(f"| Severity | **{sev.upper()}** |")
        if cvss.vector:
            md.append(f"| CVSS v3.1 | {cvss.score} ({cvss.rating}) — `{cvss.vector}` |")
        md.append(f"| Status | {f['status']} |")
        md.append(f"| CWE | CWE-79 |")
        md.append(f"| Affected URL | `{f['url']}` |")
        if f["parameter"]:
            md.append(f"| Parameter | `{f['parameter']}` |")
        if context:
            md.append(f"| Injection context | {context} |")
        md.append(f"| Instances recorded | {f['instance_count']} |")
        md.append("")

        if f["status"] != "verified":
            md.append("> ⚠️ **UNVERIFIED.** Execution was not confirmed by the browser "
                      "verifier. Reproduce manually before submitting.\n")

        # Description / root cause (client-facing)
        md.append("## Summary")
        md.append(f["description"] or "")
        md.append("")
        md.append("## Root cause & impact")
        md.append(explain_finding(f, audience="client"))
        md.append("")

        # Payload
        if f["payload"]:
            md.append("## Payload")
            md.append("```")
            md.append(str(f["payload"]))
            md.append("```")
            md.append("")

        # Reproduction
        md.append("## Reproduction steps")
        for i, step in enumerate(_repro_steps(f, evidence), 1):
            md.append(f"{i}. {step}")
        md.append("")

        # Visual PoC
        if f["poc_screenshot"] and Path(f["poc_screenshot"]).exists():
            md.append("## Proof of concept (visual)")
            md.append(f"![PoC screenshot]({_rel_to(self.out_dir, f['poc_screenshot'])})")
            if evidence.get("dialog_text"):
                md.append(f"\n*The browser raised a dialog reading:* `{evidence['dialog_text']}`")
            md.append("")

        # CSP issue detail
        if subtype == "csp" and evidence.get("issues"):
            md.append("## CSP weaknesses")
            md.append("| Severity | Directive | Issue | Detail |")
            md.append("|---|---|---|---|")
            for iss in evidence["issues"]:
                md.append(f"| {iss.get('severity')} | `{iss.get('directive')}` | "
                          f"{iss.get('issue')} | {iss.get('detail')} |")
            md.append("")

        # HTTP request/response
        if f["request"]:
            md.append("## HTTP request")
            md.append("```http")
            md.append(str(f["request"])[:6000])
            md.append("```")
            md.append("")
        if f["response"]:
            md.append("## HTTP response (truncated)")
            md.append("```http")
            md.append(str(f["response"])[:6000])
            md.append("```")
            md.append("")

        # Remediation
        md.append("## Remediation")
        md.append(rem.summary)
        md.append("")
        md.append(f"**Correct fix (primary):** {rem.output_encoding}")
        md.append("")
        md.append("**Defence in depth:**")
        for d in rem.defence_in_depth:
            md.append(f"- {d}")
        md.append("")

        # References
        md.append("## References")
        for ref in rem.references:
            md.append(f"- {ref}")
        md.append("")

        # Learner notes (clearly marked to remove before submitting)
        md.append('<div class="learning">')
        md.append("## 🧑‍🎓 Learning notes (for the researcher — remove before submitting)")
        md.append(explain_finding(f, audience="learner"))
        md.append("</div>")
        md.append("")
        return "\n".join(md)

    # -- consolidated ------------------------------------------------------
    def _consolidated_markdown(self, findings, per_finding_md) -> str:
        cfg = self.ctx.config
        now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        md: list[str] = []
        md.append(f"# Security assessment — {cfg.name}")
        md.append("")
        md.append(f"*Platform:* {cfg.platform}  |  *Generated:* {now}")
        md.append("")
        md.append("## Scope tested")
        for s in cfg.in_scope_summary:
            md.append(f"- `{s}`")
        md.append("")

        # Summary table
        md.append("## Findings overview")
        md.append("| ID | Title | Type | Severity | Status |")
        md.append("|---|---|---|---|---|")
        for f in findings:
            cvss = score_for_subtype(f["subtype"] or "reflected")
            sev = cvss.rating if (f["subtype"] != "csp") else f["severity"]
            md.append(f"| {f['id']} | {f['title']} | {f['subtype']} | "
                      f"{(sev or f['severity']).upper()} | {f['status']} |")
        md.append("")

        verified = sum(1 for f in findings if f["status"] == "verified")
        md.append(f"**{len(findings)} finding(s); {verified} verified.**")
        md.append("\n---\n")

        # Each finding in full.
        for _, finding_md in per_finding_md:
            md.append(finding_md)
            md.append("\n---\n")
        return "\n".join(md)

    # -- PDF via headless Chromium ----------------------------------------
    def _render_pdf(self, markdown_text: str, out_pdf: Path) -> bool:
        try:
            import markdown as md_lib
            from playwright.sync_api import sync_playwright
        except Exception:
            self.log.warning("Markdown/Playwright not available — skipping PDF %s", out_pdf.name)
            return False

        html_body = md_lib.markdown(
            markdown_text, extensions=["tables", "fenced_code", "md_in_html"]
        )
        html_body = _inline_images(html_body, self.out_dir)
        html = f"<!doctype html><html><head><meta charset='utf-8'><style>{_CSS}</style></head><body>{html_body}</body></html>"

        try:
            with sync_playwright() as p:
                browser = p.chromium.launch(args=["--no-sandbox", "--disable-dev-shm-usage"])
                page = browser.new_context().new_page()
                page.set_content(html, wait_until="load")
                page.pdf(path=str(out_pdf), format="A4", print_background=True,
                         margin={"top": "1cm", "bottom": "1cm", "left": "1cm", "right": "1cm"})
                browser.close()
            return True
        except Exception as exc:
            self.log.warning("PDF render failed for %s: %s", out_pdf.name, exc)
            return False


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _load_evidence(raw) -> dict:
    if isinstance(raw, dict):
        return raw
    try:
        return json.loads(raw) if raw else {}
    except Exception:
        return {}


def _rel_to(base: Path, target: str) -> str:
    """A relative path from the report dir to a file (for Markdown viewing)."""
    try:
        import os
        return os.path.relpath(target, base)
    except Exception:
        return target


def _repro_steps(f: Any, evidence: dict) -> list[str]:
    subtype = f["subtype"] or "reflected"
    url, param, payload = f["url"], f["parameter"], f["payload"]
    test_url = evidence.get("test_url") or evidence.get("poc_url") or ""
    if subtype == "dom":
        return [
            f"Navigate to `{url}` with the payload in the URL fragment (after `#`).",
            f"Example: `{test_url or url + '#<payload>'}`",
            "The client-side script writes the fragment into a dangerous sink and the "
            "benign `alert()` fires (see PoC).",
        ]
    if subtype == "blind":
        return [
            f"Submit the out-of-band payload into the `{param}` input at `{url}`.",
            "Wait for the stored content to be rendered in a (possibly privileged) view.",
            "Observe the callback recorded by the interactsh listener (correlation id in evidence).",
        ]
    if subtype == "csp":
        return [
            f"Fetch `{url}` and inspect the `Content-Security-Policy` response header.",
            "Compare it against the weaknesses listed above.",
        ]
    return [
        f"Open `{(url or '').split('?')[0]}` in a browser.",
        f"Set the `{param}` parameter to the payload below.",
        f"Full request URL: `{test_url or url}`",
        "Observe the benign `alert()` fire, confirming script execution (see PoC).",
    ]


def _inline_images(html: str, base_dir: Path) -> str:
    """Replace <img src="local"> with base64 data URIs so PDFs are self-contained."""
    def repl(match: re.Match) -> str:
        src = match.group(1)
        if src.startswith("data:") or src.startswith("http"):
            return match.group(0)
        path = (base_dir / src).resolve()
        if not path.exists():
            path = Path(src)
        if not path.exists():
            return match.group(0)
        try:
            data = base64.b64encode(path.read_bytes()).decode("ascii")
            return f'<img src="data:image/png;base64,{data}"'
        except Exception:
            return match.group(0)

    return re.sub(r'<img src="([^"]+)"', repl, html)
